<p>To ensure a consistent data format throughout each data columns, I will be changing some data columns to make it visually appealing and consistent.</p>

<hr/>
<h3>2.9.1 Identifying Categorical Data In Datasets</h3>

<p>Before being able to standardise and format the Categorical Data of each Dataset, we will firstly need to identify each of the Categorical Data within the Dataset and subsequently, identify the changes that needs to be made to the data within the Categorical Data Column. The potential results that we might observe and the subsequent action plan has been listed below.</p>
<br/>
<span style="color:red"><p><strong><u>Data Format / Structure Not Standardised</u></strong></p></span>
<ul>
    <li>Proceed to address and correct the Data Format / Structure for the Data Column in question.</li>
</ul>
<span style="color:green"><p><strong><u>Data Format / Structure Standardised</u></strong></p></span>
<ul>
    <li>Proceed with checking next Dataset and / or correct any Incorrect / Unsuitable Data Types found in other Datasets.</li>
</ul>
<br/>
<p>With the action plan listed above, I will be proceeding to check for potential Data Format / Structure Not Standardised within each of the Datasets.</p>

<hr/>
<h4>2.9.1.1 Identifying Categorical Data In Dataset 1</h4>

<p>We will proceed with checking the Categorical Data within Dataset 1 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [463]:
# ----------- Selecting All Categorical Data ----------- #
df1_objects = df1.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df1_objects[col].dropna()) for col in df1_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df1_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df1_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df1_categorical_data

,university,school,degree
0,Nanyang Technological University,College of Business (Nanyang Business School),Accountancy
1,National University of Singapore,College of Design and Engineering,Accountancy (3-yr direct Honours Programme)
2,Singapore Institute of Technology,College of Engineering,Accountancy (4-year programme)
3,Singapore Management University,"College of Humanities, Arts & Social Sciences",Accountancy (4-year programme) Cum Laude and a...
4,Singapore University of Social Sciences,College of Science,Accountancy (4-years programme)
...,...,...,...
320,,,Social Sciences (Cum Laude and above)
321,,,Social Sciences Cum Laude and above
322,,,Sociology
323,,,Sport Science and Management
324,,,Sports Science and Management

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 1 and we have determined that there is no need to make any changes to any of the Categorical Data due to most of it being redundant or already standardised. Therefore, the conclusion for this operation based off the observations is that the <span style="color:green"><strong><u>Data Format / Structure Standardised</u></strong></span>.</p>

<hr/>
<h4>2.9.1.2 Identifying Categorical Data In Dataset 2</h4>

<p>We will proceed with checking the Categorical Data within Dataset 2 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [467]:
# ----------- Selecting All Categorical Data ----------- #
df2_objects = df2.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df2_objects[col].dropna()) for col in df2_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df2_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df2_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df2_categorical_data

Empty DataFrame
Columns: []
Index: []

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 2 and we have determined that there is no need to make any changes to any of the Categorical Data due there not being Categorical Data in the first place. Therefore, the conclusion for this operation based off the observations is that the <span style="color:green"><strong><u>Data Format / Structure Standardised</u></strong></span> due to no Categorical Data present within the dataset.</p>

<hr/>
<h4>2.9.1.3 Identifying Categorical Data In Dataset 3</h4>

<p>We will proceed with checking the Categorical Data within Dataset 3 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [471]:
# ----------- Selecting All Categorical Data ----------- #
df3_objects = df3.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df3_objects[col].dropna()) for col in df3_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df3_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df3_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df3_categorical_data

      sex                   highest_qualification
0  female                                  degree
1    male  diploma and professional qualification
2                                 lower secondary
3                   post-secondary (non-tertiary)
4                               primary and below
5                                       secondary

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 3 and we have determined that there is a need to re-format some of the Data due to them being not visually appealing. Therefore, the conclusion for this operation based off the observations is that the <span style="color:red"><strong><u>Data Format / Structure Not Standardised</u></strong></span> due to room for improvements within the Data in the Categorical Data Columns to make it more visually appealing. The mapping has been indicated below.</p>
<br/>
<p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
<p><strong><u>highest_qualification</u></strong></p>
<ul>
    <li><span style="color:red"><strong>degree</strong></span> &#10132; <span style="color:green"><strong>Degree</strong></span></li>
    <li><span style="color:red"><strong>diploma and professional qualification</strong></span> &#10132; <span style="color:green"><strong>Diploma & Professional Qualification</strong></span></li>
    <li><span style="color:red"><strong>lower secondary</strong></span> &#10132; <span style="color:green"><strong>Lower Secondary</strong></span></li>
    <li><span style="color:red"><strong>post-secondary (non-tertiary)</strong></span> &#10132; <span style="color:green"><strong>Post-Secondary (Non-Tertiary)</strong></span></li>
    <li><span style="color:red"><strong>primary and below</strong></span> &#10132; <span style="color:green"><strong>Primary & Below</strong></span></li>
    <li><span style="color:red"><strong>secondary</strong></span> &#10132; <span style="color:green"><strong>Secondary</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to inspect the next dataset for potential improvements to be done on the Categorical Data.</p>

<hr/>
<h4>2.9.1.4 Identifying Categorical Data In Dataset 4</h4>

<p>We will proceed with checking the Categorical Data within Dataset 4 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [475]:
# ----------- Selecting All Categorical Data ----------- #
df4_objects = df4.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df4_objects[col].dropna()) for col in df4_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df4_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df4_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df4_categorical_data

       sex        age
0   female      15-19
1     male      20-24
2               25-29
3               30-34
4               35-39
5               40-44
6               45-49
7               50-54
8               55-59
9               60-64
10              65-69
11          70 & Over

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 4 and we have determined that there is a need to re-format some of the Data due to them being not visually appealing. Therefore, the conclusion for this operation based off the observations is that the <span style="color:red"><strong><u>Data Format / Structure Not Standardised</u></strong></span> due to room for improvements within the Data in the Categorical Data Columns to make it more visually appealing. The mapping has been indicated below.</p>
<br/>
<p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to inspect the next dataset for potential improvements to be done on the Categorical Data.</p>

<hr/>
<h4>2.9.1.5 Identifying Categorical Data In Dataset 5</h4>

<p>We will proceed with checking the Categorical Data within Dataset 5 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [479]:
# ----------- Selecting All Categorical Data ----------- #
df5_objects = df5.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df5_objects[col].dropna()) for col in df5_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df5_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df5_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df5_categorical_data

      sex        age
0  female      15-24
1    male      25-54
2              25-64
3              55-64
4          65 & Over

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 5 and we have determined that there is a need to re-format some of the Data due to them being not visually appealing. Therefore, the conclusion for this operation based off the observations is that the <span style="color:red"><strong><u>Data Format / Structure Not Standardised</u></strong></span> due to room for improvements within the Data in the Categorical Data Columns to make it more visually appealing. The mapping has been indicated below.</p>
<br/>
<p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to inspect the next dataset for potential improvements to be done on the Categorical Data.</p>

<hr/>
<h4>2.9.1.6 Identifying Categorical Data In Dataset 6</h4>

<p>We will proceed with checking the Categorical Data within Dataset 6 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [483]:
# ----------- Selecting All Categorical Data ----------- #
df6_objects = df6.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df6_objects[col].dropna()) for col in df6_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df6_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df6_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df6_categorical_data

    Gender                                         Industry
0   Female                                A, B, D, E Others
1     Male                                  C Manufacturing
2                                            F Construction
3                                G Wholesale & Retail Trade
4                                              G-U Services
5                                H Transportation & Storage
6                           I Accommodation & Food Services
7                            J Information & Communications
8                          K Financial & Insurance Services
9                                    L Real Estate Services
10                                  M Professional Services
11                      N Administrative & Support Services
12                   O, P Public Administration & Education
13                               Q Health & Social Services
14                       R Arts, Entertainment & Recreation
15          S-U Other Community, Social & Personal Services

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 6 and we have determined that there is a need to re-format some of the Data due to them being not visually appealing. Therefore, the conclusion for this operation based off the observations is that the <span style="color:red"><strong><u>Data Format / Structure Not Standardised</u></strong></span> due to room for improvements within the Data in the Categorical Data Columns to make it more visually appealing. The mapping has been indicated below.</p>
<br/>
<p><strong><u>Industry</u></strong></p>
<ul>
    <li><span style="color:red"><strong>A, B, D, E Others</strong></span> &#10132; <span style="color:green"><strong>Others</strong></span></li>
    <li><span style="color:red"><strong>C Manufacturing</strong></span> &#10132; <span style="color:green"><strong>Manufacturing</strong></span></li>
    <li><span style="color:red"><strong>F Construction</strong></span> &#10132; <span style="color:green"><strong>Construction</strong></span></li>
    <li><span style="color:red"><strong>G Wholesale & Retail Trade</strong></span> &#10132; <span style="color:green"><strong>Wholesale & Retail Trade</strong></span></li>
    <li><span style="color:red"><strong>G-U Services</strong></span> &#10132; <span style="color:green"><strong>Services</strong></span></li>
    <li><span style="color:red"><strong>H Transportation & Storage</strong></span> &#10132; <span style="color:green"><strong>Transportation & Storage</strong></span></li>
    <li><span style="color:red"><strong>I Accommodation & Food Services</strong></span> &#10132; <span style="color:green"><strong>Accommodation & Food Services</strong></span></li>
    <li><span style="color:red"><strong>J Information & Communications</strong></span> &#10132; <span style="color:green"><strong>Information & Communications</strong></span></li>
    <li><span style="color:red"><strong>K Financial & Insurance Services</strong></span> &#10132; <span style="color:green"><strong>Financial & Insurance Services</strong></span></li>
    <li><span style="color:red"><strong>L Real Estate Services/strong></span> &#10132; <span style="color:green"><strong>"Real Estate Services/strong></span></li>
    <li><span style="color:red"><strong>M Professional Servicesstrong></span> &#10132; <span style="color:green"><strong>Professional Services</strong></span></li>
    <li><span style="color:red"><strong>N Administrative & Support Services</strong></span> &#10132; <span style="color:green"><strong>Administrative & Support Services</strong></span></li>
    <li><span style="color:red"><strong>O, P Public Administration & Education</strong></span> &#10132; <span style="color:green"><strong>Public Administration & Education</strong></span></li>
    <li><span style="color:red"><strong>Q Health & Social Services</strong></span> &#10132; <span style="color:green"><strong>Health & Social Services</strong></span></li>
    <li><span style="color:red"><strong>R Arts, Entertainment & Recreation</strong></span> &#10132; <span style="color:green"><strong>Arts, Entertainment & Recreation</strong></span></li>
    <li><span style="color:red"><strong>S-U Other Community, Social & Personal Services</strong></span> &#10132; <span style="color:green"><strong>Other Community, Social & Personal Services</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to address the potential improvements to be done on the Categorical Data.</p>

<hr/>
<h4>2.9.1.7 Identifying Categorical Data In Dataset 7</h4>

<p>We will proceed with checking the Categorical Data within Dataset 7 to observe for potential improvements to the Categorical Data. This operation will be conducted in the cell below.</p>

In [487]:
# ----------- Selecting All Categorical Data ----------- #
df7_objects = df7.select_dtypes(include=['object'])

# ----------- Storing All Categorical Data In Dictionary ----------- #
categorical_data = {col: np.unique(df7_objects[col].dropna()) for col in df7_objects.columns}

# ----------- Converting All Unique Categorical Data Into DataFrame ----------- #
df7_categorical_data = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categorical_data.items()]))

# ----------- Filling All NaN Data With Space ----------- #
df7_categorical_data.fillna('', inplace=True)

# ----------- Displaying DataFrame ----------- #
df7_categorical_data

Empty DataFrame
Columns: []
Index: []

<p>With reference to the output of the DataFrame above, we are able to see all the Categorical Data within Dataset 7 and we have determined that there is no need to make any changes to any of the Categorical Data due there not being Categorical Data in the first place. Therefore, the conclusion for this operation based off the observations is that the <span style="color:green"><strong><u>Data Format / Structure Standardised</u></strong></span> due to no Categorical Data present within the dataset.</p>

<hr/>
<h3>2.9.2 Applying Standardisation For Identified Categorical Data Columns</h3>

<p>As previously identifdied, we will be addressing each of the Categorical Data Column's Data strictly in accordance with the mapping laid out previosuly. This mapping is indicated and listed below and will be strictly followed throughout this section.</p>
<br/>
<p><strong><u>Dataset 1</u></strong></p>
<ul>
    <li>NONE</li>
</ul>
<p><strong><u>Dataset 2</u></strong></p>
<ul>
    <li>NONE</li>
</ul>
<p><strong><u>Dataset 3</u></strong></p>
<ul>
    <p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
    <br/>
<p><strong><u>highest_qualification</u></strong></p>
<ul>
    <li><span style="color:red"><strong>degree</strong></span> &#10132; <span style="color:green"><strong>Degree</strong></span></li>
    <li><span style="color:red"><strong>diploma and professional qualification</strong></span> &#10132; <span style="color:green"><strong>Diploma & Professional Qualification</strong></span></li>
    <li><span style="color:red"><strong>lower secondary</strong></span> &#10132; <span style="color:green"><strong>Lower Secondary</strong></span></li>
    <li><span style="color:red"><strong>post-secondary (non-tertiary)</strong></span> &#10132; <span style="color:green"><strong>Post-Secondary (Non-Tertiary)</strong></span></li>
    <li><span style="color:red"><strong>primary and below</strong></span> &#10132; <span style="color:green"><strong>Primary & Below</strong></span></li>
    <li><span style="color:red"><strong>secondary</strong></span> &#10132; <span style="color:green"><strong>Secondary</strong></span></li>
</ul>
</ul>
<p><strong><u>Dataset 4</u></strong></p>
<ul>
    <p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
</ul>
<p><strong><u>Dataset 5</u></strong></p>
<ul>
    <p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
</ul>
<p><strong><u>Dataset 6</u></strong></p>
<ul>
<p><strong><u>Industry</u></strong></p>
<ul>
    <li><span style="color:red"><strong>A, B, D, E Others</strong></span> &#10132; <span style="color:green"><strong>Others</strong></span></li>
    <li><span style="color:red"><strong>C Manufacturing</strong></span> &#10132; <span style="color:green"><strong>Manufacturing</strong></span></li>
    <li><span style="color:red"><strong>F Construction</strong></span> &#10132; <span style="color:green"><strong>Construction</strong></span></li>
    <li><span style="color:red"><strong>G Wholesale & Retail Trade</strong></span> &#10132; <span style="color:green"><strong>Wholesale & Retail Trade</strong></span></li>
    <li><span style="color:red"><strong>G-U Services</strong></span> &#10132; <span style="color:green"><strong>Services</strong></span></li>
    <li><span style="color:red"><strong>H Transportation & Storage</strong></span> &#10132; <span style="color:green"><strong>Transportation & Storage</strong></span></li>
    <li><span style="color:red"><strong>I Accommodation & Food Services</strong></span> &#10132; <span style="color:green"><strong>Accommodation & Food Services</strong></span></li>
    <li><span style="color:red"><strong>J Information & Communications</strong></span> &#10132; <span style="color:green"><strong>Information & Communications</strong></span></li>
    <li><span style="color:red"><strong>K Financial & Insurance Services</strong></span> &#10132; <span style="color:green"><strong>Financial & Insurance Services</strong></span></li>
    <li><span style="color:red"><strong>L Real Estate Services/strong></span> &#10132; <span style="color:green"><strong>"Real Estate Services/strong></span></li>
    <li><span style="color:red"><strong>M Professional Servicesstrong></span> &#10132; <span style="color:green"><strong>Professional Services</strong></span></li>
    <li><span style="color:red"><strong>N Administrative & Support Services</strong></span> &#10132; <span style="color:green"><strong>Administrative & Support Services</strong></span></li>
    <li><span style="color:red"><strong>O, P Public Administration & Education</strong></span> &#10132; <span style="color:green"><strong>Public Administration & Education</strong></span></li>
    <li><span style="color:red"><strong>Q Health & Social Services</strong></span> &#10132; <span style="color:green"><strong>Health & Social Services</strong></span></li>
    <li><span style="color:red"><strong>R Arts, Entertainment & Recreation</strong></span> &#10132; <span style="color:green"><strong>Arts, Entertainment & Recreation</strong></span></li>
    <li><span style="color:red"><strong>S-U Other Community, Social & Personal Services</strong></span> &#10132; <span style="color:green"><strong>Other Community, Social & Personal Services</strong></span></li>
</ul>
</ul>
<p><strong><u>Dataset 7</u></strong></p>
<ul>
    <li>NONE</li>
</ul>
<br/>
<p>With the mapping liad out, we will proceed to conduct the operation to re-format all the Categorical Data listed above.</p>

<hr/>
<h4>2.9.2.2 Standardising Categorical Data In Dataset 4</h4>

<p>As previously identified, we will be mapping out and re-formating the following Categorical Data Column's Data. The mapping is listed below.</p>
<br/>
<p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to conducting the mapping operation in the cell below.</p>

In [493]:
# ------------ Defining Mapping Dictionary ------------ #
rename_mapping = {
    'sex': {
        'female': 'Female',
        'male': 'Male'
    }
}

# ---------- Applying Mapping To DataFrame ---------- #
df4.replace(rename_mapping, inplace=True)

# ----------- Displaying DataFrame ----------- #
df4.head(5)

   year   sex    age  resident_labour_force
0  1991  Male  15-19                  36900
1  1991  Male  20-24                  99400
2  1991  Male  25-29                 134500
3  1991  Male  30-34                 143300
4  1991  Male  35-39                 131000

<p>With the output of the DataFrame above, we are able to observe and verify that the mapping operation have been conducted successfully on the DataFrame.</p>

<hr/>
<h4>2.9.2.3 Standardising Categorical Data In Dataset 5</h4>

<p>As previously identified, we will be mapping out and re-formating the following Categorical Data Column's Data. The mapping is listed below.</p>
<br/>
<p><strong><u>sex</u></strong></p>
<ul>
    <li><span style="color:red"><strong>female</strong></span> &#10132; <span style="color:green"><strong>Female</strong></span></li>
    <li><span style="color:red"><strong>male</strong></span> &#10132; <span style="color:green"><strong>Male</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to conducting the mapping operation in the cell below.</p>

In [497]:
# ------------ Defining Mapping Dictionary ------------ #
rename_mapping = {
    'sex': {
        'female': 'Female',
        'male': 'Male'
    }
}

# ---------- Applying Mapping To DataFrame ---------- #
df5.replace(rename_mapping, inplace=True)

# ----------- Displaying DataFrame ----------- #
df5.head(5)

   year   sex        age  resident_labour_force_participation_rate
0  1991  Male      25-64                                      92.6
1  1991  Male      15-24                                      55.9
2  1991  Male      25-54                                      97.5
3  1991  Male      55-64                                      59.7
4  1991  Male  65 & Over                                      19.9

<p>With the output of the DataFrame above, we are able to observe and verify that the mapping operation have been conducted successfully on the DataFrame.</p>

<hr/>
<h4>2.9.2.4 Standardising Categorical Data In Dataset 6</h4>

<p>As previously identified, we will be mapping out and re-formating the following Categorical Data Column's Data. The mapping is listed below.</p>
<br/>
<p><strong><u>Industry</u></strong></p>
<ul>
    <li><span style="color:red"><strong>A, B, D, E Others</strong></span> &#10132; <span style="color:green"><strong>Others</strong></span></li>
    <li><span style="color:red"><strong>C Manufacturing</strong></span> &#10132; <span style="color:green"><strong>Manufacturing</strong></span></li>
    <li><span style="color:red"><strong>F Construction</strong></span> &#10132; <span style="color:green"><strong>Construction</strong></span></li>
    <li><span style="color:red"><strong>G Wholesale & Retail Trade</strong></span> &#10132; <span style="color:green"><strong>Wholesale & Retail Trade</strong></span></li>
    <li><span style="color:red"><strong>G-U Services</strong></span> &#10132; <span style="color:green"><strong>Services</strong></span></li>
    <li><span style="color:red"><strong>H Transportation & Storage</strong></span> &#10132; <span style="color:green"><strong>Transportation & Storage</strong></span></li>
    <li><span style="color:red"><strong>I Accommodation & Food Services</strong></span> &#10132; <span style="color:green"><strong>Accommodation & Food Services</strong></span></li>
    <li><span style="color:red"><strong>J Information & Communications</strong></span> &#10132; <span style="color:green"><strong>Information & Communications</strong></span></li>
    <li><span style="color:red"><strong>K Financial & Insurance Services</strong></span> &#10132; <span style="color:green"><strong>Financial & Insurance Services</strong></span></li>
    <li><span style="color:red"><strong>L Real Estate Services/strong></span> &#10132; <span style="color:green"><strong>"Real Estate Services/strong></span></li>
    <li><span style="color:red"><strong>M Professional Servicesstrong></span> &#10132; <span style="color:green"><strong>Professional Services</strong></span></li>
    <li><span style="color:red"><strong>N Administrative & Support Services</strong></span> &#10132; <span style="color:green"><strong>Administrative & Support Services</strong></span></li>
    <li><span style="color:red"><strong>O, P Public Administration & Education</strong></span> &#10132; <span style="color:green"><strong>Public Administration & Education</strong></span></li>
    <li><span style="color:red"><strong>Q Health & Social Services</strong></span> &#10132; <span style="color:green"><strong>Health & Social Services</strong></span></li>
    <li><span style="color:red"><strong>R Arts, Entertainment & Recreation</strong></span> &#10132; <span style="color:green"><strong>Arts, Entertainment & Recreation</strong></span></li>
    <li><span style="color:red"><strong>S-U Other Community, Social & Personal Services</strong></span> &#10132; <span style="color:green"><strong>Other Community, Social & Personal Services</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to conducting the mapping operation in the cell below.</p>

<p>As previously identified, we will be mapping out and re-formating the following Categorical Data Column's Data. The mapping is listed below.</p>
<br/>
<p><strong><u>Industry</u></strong></p>
<ul>
    <li><span style="color:red"><strong>A, B, D, E Others</strong></span> &#10132; <span style="color:green"><strong>Others</strong></span></li>
    <li><span style="color:red"><strong>C Manufacturing</strong></span> &#10132; <span style="color:green"><strong>Manufacturing</strong></span></li>
    <li><span style="color:red"><strong>F Construction</strong></span> &#10132; <span style="color:green"><strong>Construction</strong></span></li>
    <li><span style="color:red"><strong>G Wholesale & Retail Trade</strong></span> &#10132; <span style="color:green"><strong>Wholesale & Retail Trade</strong></span></li>
    <li><span style="color:red"><strong>G-U Services</strong></span> &#10132; <span style="color:green"><strong>Services</strong></span></li>
    <li><span style="color:red"><strong>H Transportation & Storage</strong></span> &#10132; <span style="color:green"><strong>Transportation & Storage</strong></span></li>
    <li><span style="color:red"><strong>I Accommodation & Food Services</strong></span> &#10132; <span style="color:green"><strong>Accommodation & Food Services</strong></span></li>
    <li><span style="color:red"><strong>J Information & Communications</strong></span> &#10132; <span style="color:green"><strong>Information & Communications</strong></span></li>
    <li><span style="color:red"><strong>K Financial & Insurance Services</strong></span> &#10132; <span style="color:green"><strong>Financial & Insurance Services</strong></span></li>
    <li><span style="color:red"><strong>L Real Estate Services</strong></span> &#10132; <span style="color:green"><strong>"Real Estate Services</strong></span></li>
    <li><span style="color:red"><strong>M Professional Services</strong></span> &#10132; <span style="color:green"><strong>Professional Services</strong></span></li>
    <li><span style="color:red"><strong>N Administrative & Support Services</strong></span> &#10132; <span style="color:green"><strong>Administrative & Support Services</strong></span></li>
    <li><span style="color:red"><strong>O, P Public Administration & Education</strong></span> &#10132; <span style="color:green"><strong>Public Administration & Education</strong></span></li>
    <li><span style="color:red"><strong>Q Health & Social Services</strong></span> &#10132; <span style="color:green"><strong>Health & Social Services</strong></span></li>
    <li><span style="color:red"><strong>R Arts, Entertainment & Recreation</strong></span> &#10132; <span style="color:green"><strong>Arts, Entertainment & Recreation</strong></span></li>
    <li><span style="color:red"><strong>S-U Other Community, Social & Personal Services</strong></span> &#10132; <span style="color:green"><strong>Other Community, Social & Personal Services</strong></span></li>
</ul>
<br/>
<p>With the mapping laid out, we will proceed to conducting the mapping operation in the cell below.</p>

In [502]:
# ------------ Defining Mapping Dictionary ------------ #
rename_mapping = {
    'A, B, D, E Others': 'Others',
    'C Manufacturing': 'Manufacturing',
    'F Construction': 'Construction',
    'G Wholesale & Retail Trade': 'Wholesale & Retail Trade',
    'G-U Services': 'Services',
    'H Transportation & Storage': 'Transportation & Storage',
    'I Accommodation & Food Services': 'Accommodation & Food Services',
    'J Information & Communications': 'Information & Communications',
    'K Financial & Insurance Services': 'Financial & Insurance Services',
    'L Real Estate Services': 'Real Estate Services',
    'M Professional Services': 'Professional Services',
    'N Administrative & Support Services': 'Administrative & Support Services',
    'O, P Public Administration & Education': 'Public Administration & Education',
    'Q Health & Social Services': 'Health & Social Services',
    'R Arts, Entertainment & Recreation': 'Arts, Entertainment & Recreation',
    'S-U Other Community, Social & Personal Services': 'Other Community, Social & Personal Services'
}

# ---------- Applying Mapping To DataFrame ---------- #
df6.replace(rename_mapping, inplace=True)

# ----------- Displaying DataFrame ----------- #
df6.head(5)

    Amt Gender                  Industry  Year
0  6105   Male             Manufacturing  2023
1  5070   Male              Construction  2023
2  5387   Male                  Services  2023
3  5168   Male  Wholesale & Retail Trade  2023
4  3435   Male  Transportation & Storage  2023

<p>With the output of the DataFrame above, we are able to observe and verify that the mapping operation have been conducted successfully on the DataFrame.</p>

<hr/>
<h2>2.10 Validating Numerical Data</h2>

<p>To ensure all Numerical Data are either '0' or a positive value, I will need to validate each data columns. Numerical Data which are below '0' will be determined as illegitimate Numerical Data and will subsequently need to be addressed. The action plan to address these illegitimate Numerical Data are listed below.</p>
<br/>
<span style="color:red"><p><strong><u>Illegitimate Numerical Data Identified</u></strong></p></span>
<ul>
    <li>Proceed to inspect the Data Row with the Illegitimate Numerical Data accordingly and address it depending on what suits best with the Dataset context.</li>
</ul>
<span style="color:green"><p><strong><u>No Illegitimate Numerical Data Identified</u></strong></p></span>
<ul>
    <li>Proceed with checking next Dataset and / or address any Illegitimate Numerical Data found in other Datasets.</li>
</ul>
<br/>
<p>With the action plan listed above, I will be proceeding to check for Abnormality Data.</p>

<hr/>
<h3>2.10.1 Verifying Numerical Data For Dataset 1</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the First Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [508]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df1.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.2 Verifying Numerical Data For Dataset 2</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Second Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [512]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df2.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.3 Verifying Numerical Data For Dataset 3</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Third Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [516]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df3.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.4 Verifying Numerical Data For Dataset 4</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Forth Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [520]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df4.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.5 Verifying Numerical Data For Dataset 5</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Fifth Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [524]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df5.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.6 Verifying Numerical Data For Dataset 6</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Sixth Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [528]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df6.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h3>2.10.7 Verifying Numerical Data For Dataset 7</h3>

<p>We will be verifying if there are any illegitimate Numerical Data within the Seventh Dataset. Should there be any illegitimate Numerical Data identified, we will proceed with the action plan listed previously which will ultimately ressolve the issue. This operation will be conducted in the cell below.</p>

In [532]:
# ---------- Selecting Numeric Columns ----------
numeric_cols = df7.select_dtypes(include=['number'])

# ---------- Counting Negative Values Per Column ----------
negative_counts_per_column = (numeric_cols < 0).sum()

# ---------- Calculating Total Negative Values ----------
total_negative_values = negative_counts_per_column.sum()

# ---------- Creating DataFrame To Store Results ----------
df_negative_counts = pd.DataFrame({
    'Column': negative_counts_per_column.index,
    'Negative Value Count': negative_counts_per_column.values
})

# ---------- Inserting Data Into DataFrame ----------
df_negative_counts.loc[len(df_negative_counts)] = ['Total', total_negative_values]

# ---------- Set "Column" As The Index ----------
df_negative_counts.set_index('Column', inplace=True)

# ---------- Function for Conditional Formatting ----------
def highlight_values(val):
    color = 'red' if val > 1 else 'green'
    return f'background-color: {color}'

# ---------- Apply Formatting to "Negative Value Count" Column ----------
df_negative_counts = df_negative_counts.style.applymap(highlight_values, subset=['Negative Value Count'])

# ---------- Display DataFrame ----------
df_negative_counts

<p>With reference to the DataFrame above, I am able to verify that there is no Illegitimate Numerical Data. This can be seen from the DataFrame where there is no Negative Value detected. Therefore, the identification has been concluded as <span style="color:green"><strong><u>No Illegitimate Numerical Data Identified.</u></strong></span></p>

<hr/>
<h2>2.11 Feature Engineering</h2>

<p>In Feature Engineering, I will be creating a few new features that will make the Data Analysis more steamlined and interpretable. This is because, new features can help in cutting down the amount of data visualisations through potentially combining 2 data columns into 1 single new data columns or creating a whole new variable. The new features created wil be dependent of each of the Dataset to suit the needs and purpose of the Dataset respectively.</p>

<hr/>
<h3>2.11.1 Feaure Engineering For Dataset 1</h3>

<p>For Dataset 1, we will be creating 2 new Features which are 'Field of Study' and 'uni_short'. These will be important when we carry out the Data Analysis and Visualisation as we are able to see the a more streamlined categorical data. This will be done through mapping.</p>

In [538]:
# ---------- Mapping Of Field Of Studies ---------- #
degree_categories = {
    "Business": ["business", "accountancy", "finance", "commerce", "management", "marketing", "economics"],
    "Engineering": ["engineering", "mechanical", "electrical", "civil", "aerospace", "chemical", "industrial"],
    "Science": ["science", "biology", "chemistry", "physics", "biomedical", "mathematics"],
    "Computer Science & IT": ["computer", "computing", "data", "artificial intelligence", "cybersecurity", "software", "information technology"],
    "Humanities & Social Sciences": ["arts", "history", "philosophy", "sociology", "psychology", "political science"],
    "Healthcare & Medicine": ["medicine", "nursing", "pharmacy", "dental", "health", "nutrition"],
    "Law": ["law", "legal", "jurisprudence"],
    "Education": ["education", "teaching", "pedagogy"],
    "Others": []
}

# ---------- Function For Classification ---------- #
def categorize_degree(degree):
    degree_lower = str(degree).lower()
    for category, keywords in degree_categories.items():
        if any(keyword in degree_lower for keyword in keywords):
            return category
    return "Others"  # Default if no match

# ---------- Applying Of Classification ---------- #
df1["Field of Study"] = df1["degree"].apply(categorize_degree)

# ---------- Mapping Of University Short Form ---------- #
university_map = {
    "Nanyang Technological University": "NTU",
    "National University of Singapore": "NUS",
    "Singapore Management University": "SMU",
    "Singapore Institute of Technology": "SIT",
    "Singapore University of Social Sciences": "SUSS",
    "Singapore University of Technology and Design": "SUTD"
}

# ---------- Applying Of Mapping ---------- #
df1['uni_short'] = df1['university'].map(university_map).fillna(df1['university'])

# ---------- Displaying DataFrame ---------- #
df1.head(5).style.background_gradient(cmap="Blues")

<p>With reference to the output of the DataFrame, we are able to see that the new Data Column has been created.</p>

<hr/>
<h1>3. Data Analysis and Visualisation</h1>